[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#2E86AB"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[runner]
magicEnabled = false

[client]
showErrorDetails = true

[scheduler]
retryTimeout = 300

[global]
developmentMode = false
